language: python

python:
    - 3.4
    # This is just for "egg_info".  All other builds are explicitly given in the matrix
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.9
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'
        - INSTALL_OPTIONAL=true
    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 3.
        - python: 3.4
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 3.4
          env: SETUP_CMD='build_sphinx -w'

        # Try with optional dependencies disabled
        - python: 3.4
          env: SETUP_CMD='test' INSTALL_OPTIONAL=false

        # Try Astropy development version
        - python: 3.4
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Try all python versions with the latest numpy
        - python: 3.4
          env: SETUP_CMD='test'

        # Currently broken: https://github.com/cta-observatory/ctapipe/pull/33#issuecomment-153979923
        # Try older numpy versions
#        - python: 3.4
#          env: NUMPY_VERSION=1.8 SETUP_CMD='test'

before_install:

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update

    # Use utf8 encoding. Should be default, but this is insurance against future changes
    - export PYTHONIOENCODING=UTF8

    # Install miniconda following instructions at http://conda.pydata.org/docs/travis.html
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # DOCUMENTATION DEPENDENCIES
    - if [[ $SETUP_CMD == build_sphinx* ]]; then sudo apt-get install graphviz texlive-latex-extra dvipng; fi

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


install:

    # CONDA
    - conda create --yes -n test -c astropy-ci-extras python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - if [[ $SETUP_CMD != egg_info ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION scipy pytest pip Cython jinja2; fi
    - if [[ $SETUP_CMD != egg_info ]]; then $PIP_INSTALL pytest-xdist; fi

    # ASTROPY
    - if [[ $SETUP_CMD != egg_info ]] && [[ $ASTROPY_VERSION == development ]]; then $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy; fi
    - if [[ $SETUP_CMD != egg_info ]] && [[ $ASTROPY_VERSION == stable ]]; then $CONDA_INSTALL astropy; fi

    # OPTIONAL DEPENDENCIES
    - if [[ $SETUP_CMD != egg_info ]] && $INSTALL_OPTIONAL; then $CONDA_INSTALL h5py scikit-image scikit-learn pandas; fi

    # DOCUMENTATION DEPENDENCIES
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL Sphinx matplotlib; fi

    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then $PIP_INSTALL coverage coveralls; fi

script:
   - export CTAPIPE_EXTRA_DIR=$PWD/ctapipe-extra
   - python setup.py $SETUP_CMD

after_success:
     - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='ctapipe/tests/coveragerc'; fi
